@startuml

'hide the spot
'hide circle

'avoid problems with angled crows feet
skinparam linetype ortho

entity "Entity01" as e01 {
  *id : bigint comment "id"
  *name : varchar(50) comment "name"
  --
  <<PK>> id
  --
  comment "e01 comment"
}

entity "Entity02" as e02 {
  *id : bigint
  *eo1_id : bigint
  *order_number : bigint
  *site : tinyint
  --
  <<KEY>> idx (e01_id)
  <<UK>> udx (site,order_number)
  <<PK>>  id
  --
   comment "table comment "
}
e01 ||..o{ e02

@enduml